### ISSUE TITLE
TVHeadend 4.0.8 vs 4.0.9

### ISSUE THREAD

**Issue by rmast** [osmc/osmc#321] opened 2016-07-30 14:05 UTC
With the TVHeadend-4.0.9 version that comes with the latest version of OSMC
I have more issues than with version 4.0.8 that's coming with OpenElec.

I already saw a discussion stating that 3.9 that came with the 'stable' June '15 version is more stable than any 4.-version.

I don't know whether OpenElec uses a patched version, or that 4.0.8 just is not as flakey as 4.0.9.

As I saw the app store uses versions to compile and versions are just bumped, it would probably be a nice-to-have to be able to select the version based on specific needs and probably also the reputation of a specific version?

**Comment by samnazarko** [comment] 2016-07-30 14:08
It's definitely notable that TVH seems to regress quite frequently

This is one of the reasons I am often reluctant to bump it. Unfortunately I know that if I revert it there will be some complaints of other breakage.

What problems are you experiencing with the current version? I can have a look and see if there's anything that we can do

Cheers

Sam

Sent from a mobile device, so please excuse the brevity of this reply

On 30 Jul 2016, at 15:05, rmast <notifications@github.com<mailto:notifications@github.com>> wrote:


With the TVHeadend-4.0.9 version that comes with the latest version of OSMC
I have more issues than with version 4.0.8 that's coming with OpenElec.

I already saw a discussion stating that 3.9 that came with the 'stable' June '15 version is more stable than any 4.-version.

I don't know whether OpenElec uses a patched version, or that 4.0.8 just is not as flakey as 4.0.9.

As I saw the app store uses versions to compile and versions are just bumped, it would probably be a nice-to-have to be able to select the version based on specific needs and probably also the reputation of a specific version?

-

**Comment by rmast** [comment] 2016-07-30 14:24
I already overwrote my SD-card with OpenElec. But OSMC/TVHeadend 4.0.9 broke on me ending up with errors like in this thread:
https://tvheadend.org/boards/5/topics/19282

The same as the writer of that issue the issue wasn't solved by rebooting. So probably 4.0.8 will also fail on me in a short time, or OpenElec has patched it somehow.

Apart from this rather blocking issue, whenever I open a stream from TVHeadend via a click on a channel-link the OSMC-version doesn't open the stream in VLC, where OpenElec does. This looks more like this very old issue https://tvheadend.org/boards/5/topics/5319

So, as newer versions of TVHeadend show old issues I also wonder whether OpenElec has patched them or made workarounds in their OS?

**Comment by rmast** [comment] 2016-07-30 19:57
By the way, I don't know whether the blocking issue came from OSCam.
The OSCam connection I used with OSMC was newcamd, but the OpenElec-Youtube-tutorials use dvbapi of a very specific version, so that could probably already solve the blocking issue. As this corrupts the system and appears at an unpredictible moment it is quite hard to reproduce instantly.

The VLC-issue was so constant that I can reproduce it quite easily. 
The VLC-connection I made was from a Asus t200tac mini-laptop via a rather low-quality WiFi-connection, which from time to time can't quite keep up with the high video-rates.

I have a spare SD-card at hand, unfortunately of lower speed, with which I could try to reproduce things if needed.

**Comment by rmast** [comment] 2016-07-31 17:08
Today I compiled TVHeadend 4.0.8 from the latest commit with that tag. The PVR HTSP TVHeadend client seems the same between OpenElec and OSMC.
OpenElec's Oscam is version 10607. I also compiled that, and copied the dvbapi-way of connecting. Opening streams via VLC does work, but when the WiFi is bad the picture is bad as well.

For the other issue I should use the system somewhat more. But my main aim was looking whether I could get a hardware transcoding on the RPi3 running before streaming upstairs... So that will be the next question to answer. By the way, I don't understand why NOOBS killed OpenElec and introduced LibreElec instead. There's lots of communities and opinions while well-tested versions are very hard to find and even disappear from NOOBS, raising the bar for any newcoming developer in the field to be able to see whether TVHeadend/OSCam is functioning at all and worth investing time.

**Comment by samnazarko** [comment] 2016-07-31 17:18
When you say you compiled TVH 4.0.8? For what platform did you compile it for? OSMC or OE?


The topic of NOOBS and OE is probably better discussed elsewhere. My understanding is that OE has not been maintained for some time and most volunteers have moved to the new LibreELEC project.


We would need to see a log or more information regarding the issues you are having for us to look at it. In particular it would be good if you could give us a small sequence of steps to replicate the problem.


________________________________

**Comment by rmast** [comment] 2016-07-31 17:33
I did compile in OSMC installed and upgraded via PINN, while I want to add some custom code that's quite hard in OpenElec, and have both on an SD-card.

I could imagine people chose for another platform, stating things as organisational structure, so your statement confirms that. However, every time a project or principle is abandonned there will be people and potential volunteers diverged and leaving the field as well.

I wonder whether the newcamd-issue would be blocking for the purpose I want the system up and running as long as I can cope with dvbapi. However lots of people on the internet struggling with Oscam-versions, newcamd and or dvbapi-protocol-issues. Even if this is not the right place to discuss such issues, the choice for what versions and how-to video's to link everything together is a thing that should concern every competing team. The only good YouTube video's that lead to a somewhat stable version are about OpenElec. The most stable OSMC, the version of june 2015 has already disappeared from the site.

**Comment by samnazarko** [comment] 2016-07-31 17:38
I am not involved with the LibreELEC or OpenELEC projects, so really can't advise there. But I am concerned with any OSMC issues and making sure that OSMC is as good as it can be.

My knowledge of TVHeadend is limited. I don't know much about CAMs or the software surrounding that. They are of questionable legality in the UK, so we cannot provide much support for it. I'd also be surprised if anyone on the team is using DVB in this way. That's one of the reasons why we haven't produced how-to videos. 

>The most stable OSMC, the version of june 2015 has already disappeared from the site.

That version is absolutely ancient, and there have been many improvements since then. We don't want users clinging to outdated versions, so we remove the public URLs from our website. You can of course still get that image from http://download.osmc.tv manually. However in the same way that you expect us to improve issues in OSMC, I would also expect you (as a user) to help us do this. Using an old version of OSMC / rolling back or not updating doesn't resolve the issue long term. It's a short term fix and it means that issues drag on for far longer than they need to.

**Comment by samnazarko** [comment] 2016-07-31 17:38
Please provide logs, and an actual verbose description of the problem, including steps on how to reproduce.

>I wonder whether the newcamd-issue would be blocking for the purpose I want the system up and running as long as I can cope with dvbapi. However lots of people on the internet struggling with Oscam-versions, newcamd and or dvbapi-protocol-issues.

This is not a bug report...

**Comment by rmast** [comment] 2016-07-31 17:51
As challenging things with questionable legality often inspires people I think it's best to find the right political way to manage that spirit to find the best synergy.
The 'unofficial' branch of OpenElec as well as many smart-TV-plugins are all following that line.

By the way, Is there any way I can use precompiled OpenElec-addon's in OSMC?

**Comment by samnazarko** [comment] 2016-07-31 17:56
We do not restrict what you can do with your system, but we can't provide support for some things, particularly when OSMC developers are not using CAM and TVH.

I imagine OE add-ons are statically compiled (ldd to confirm) as they use the Kodi repo to handle binaries, so you probably *can* run them on OSMC without issue. 

Closing, as this bug tracker is for confirmed bug reports with reproduction steps.

**Closed by samnazarko** 2016-07-31 17:56 UTC
