### ISSUE TITLE
Wifi settings not saved..

### ISSUE THREAD

**Issue by alanrburns** [osmc/osmc#333] opened 2016-10-19 07:02 UTC
I have tried to use the OSMC installer to pre-configure wifi, Booted is up to find no wifi enabled and no settings saved
I have configured wifi manually 4 times now and after reboot wifi is disabled again and no settings saved.
Will this ever work properly?

**Comment by samnazarko** [comment] 2016-10-19 12:15
It already works properly for a large number of users.

Are you sure your WiFi adapter is working properly?

Closing until you provide necessary logs to prove this is a bug

**Closed by samnazarko** 2016-10-19 12:15 UTC

**Comment by alanrburns** [comment] 2016-10-19 22:08
It is a PI 3 it has built in wifi.
The installer was newly downloaded and the image is the latest.
It connects when I configure it manually.
When I reboot it is back to defaults.

What log do you want?
I went through the filesystem and could not see any information in logs.

**Comment by samnazarko** [comment] 2016-10-19 22:12
>When I reboot it is back to defaults.

Bad SD, PSU or both.

**Comment by alanrburns** [comment] 2016-10-19 23:06
No I have used different SD cards and PSU..
It works with Rasbian.. 

Where is the config stored?  
What log do you want?

**Comment by samnazarko** [comment] 2016-10-19 23:08
Raspbian uses a different connection manager. My understanding was that the issue was regarding OSMC.

As mentioned previously, until this is confirmed as a *bug*, I would prefer to see this problem discussed elsewhere (forum). This can be reopened if this is a confirmed bug. 

Please see our Wiki on how to provide appropriate logs.

**Comment by alanrburns** [comment] 2016-10-19 23:16
I tested Rasbian on the SD cards to prove they work.

Maybe you should use a better connection manager like the one Rasbian uses..
It seems to work better.
Always fun how dismissive devs can be..
Thanks for not helping..

**Comment by samnazarko** [comment] 2016-10-19 23:23
We treat every response with great care. We replied to you promptly, and we will continue to investigate this thoroughly. It's in our interest to ensure OSMC works on as wide a variety of hardware as possible, and we're willing to work with users to ensure this remains the case. 

However without a log, your report is much akin to saying your car won't start. There's a ton of reasons why that may be the case. Start a forum post with a debug log, and we promise we'll look at it and identify the issue. 

Otherwise, your reports are not too helpful in identifying the problem. If WiFi was a huge problem with OSMC, we're sure we'd have more than one report about this. I would also recommend checking your power supply is sufficient. OSMC will consume more power than Raspbian as the workload (playing media) is a different workload. 

My personal assumption is that people on GitHub are also devs, especially given your forking history. Help us help you.

**Comment by saperlot** [comment] 2017-05-08 19:03
I think there is a general issue with saving new configurations maybe especially on rpis. I had hope that this issue was beeing fixed with the march release. I am now looking here for fixed issues and this bug report seems to be similar. 
Have an issue with setting automatic power off. It is set to 10 mins. But it shut downs every 5. No chance to change over the gui. I also had issues with setting up CEC controller. Changes weren't stored. I had to open up the actual file to make my changes.. it works but there is still something strange going on. Maybe an issue with file permissions?
Had the case after updating from 16 to 17. Then i did a complete new install. But without luck. Was there anything fixed in that area?

**Comment by samnazarko** [comment] 2017-05-08 19:04
Start a forum post with debug logs

Sent from a mobile device, so please excuse the brevity of this reply

On 8 May 2017, at 20:03, saperlot <notifications@github.com<mailto:notifications@github.com>> wrote:


I think there is a general issue with saving new configurations maybe especially on rpis. I had hope that this issue was beeing fixed with the march release. I am now looking here for fixed issues and this bug report seems to be similar.
Have an issue with setting automatic power off. It is set to 10 mins. But it shut downs every 5. No chance to change over the gui. I also had issues with setting up CEC controller. Changes weren't stored. I had to open up the actual file to make my changes.. it works but there is still something strange going on. Maybe an issue with file permissions?
Had the case after updating from 16 to 17. Then i did a complete new install. But without luck. Was there anything fixed in that area?

-
