### ISSUE TITLE
Raspberry Pi: Please add i2c-gpio kernel module for HyperPixel touchscreen support

### ISSUE THREAD

**Issue by Gadgetoid** [osmc/osmc#446] opened 2018-06-06 15:18 UTC
Ahoy!

OSMC looks great on HyperPixel, but our users have reported the touchscreen not functioning. I've done some digging, and aside from the lack of RPi.GPIO (which can be fixed by installing/compiling from pip) there's no i2c-gpio module. This is used to set up a software i2c bus on BCM 10 and BCM 11 and communicate with the touch controller.

Is it possible to enable I2C_GPIO support as a builtin/module? Should be a one-line change to the relevant kernel configs:

```
CONFIG_I2C_GPIO=m
```

Cheers!

**Comment by samnazarko** [comment] 2018-06-06 15:20
Hi Phil,

I'll make this change in the next update

Cheers

Sam

**Comment by Gadgetoid** [comment] 2018-06-06 15:22
It's a long shot and possibly worthy of a separate issue- but could you also include RPi.GPIO as standard? People seem keen to use our add-ons as inputs/outputs for OSMC and I think some cool stuff could be done if that little bit of friction was eliminated.

**Comment by Gadgetoid** [comment] 2018-06-06 15:32
I was just digging through the codebase trying to figure out how the build system works when I saw https://github.com/osmc/osmc/blob/master/tools/appstore-parser/build.sh and arrived at a similar conclusion.

Looks like I've got some learning to do! Thank you.

**Comment by samnazarko** [comment] 2018-06-06 15:33
The App Store is in a (slightly dragging) state of redesign to make it easier to manage, which is why it won't be included for a while yet, but it's the best approach for the long term.

**Comment by samnazarko** [comment] 2018-06-06 22:36
I've now added this in c59105bd750c4928b5b409b8c7638a79c1808c45.

I'd appreciate it if you could test this and provide feedback before we potentially release this as an update to other users. To test this update:

1. [Login via the command line](https://osmc.tv/wiki/general/accessing-the-command-line/)
2. Edit the file ```/etc/apt/sources.list```
3. Add the following line: ```deb http://apt.osmc.tv stretch-devel main```
4. Run the following commands to update: ```sudo apt-get update && sudo apt-get dist-upgrade && reboot```
5. Your system should have have received the update. 

Please see if the issue is resolved.

I also recommend you edit ```/etc/apt/sources.list``` again and remove the line that you added after updating. This will return you to the normal update channel. 

We should have this out as a stable update in the next day or two. Thanks for the report.

I'll close the issue as the initial issue is resolved, but will ticket your request for RPI.GPIO under JIRA so it's not forgotten.

Cheers

Sam

**Closed** 2018-06-06 22:36 UTC

**Comment by meodai** [comment] 2019-01-31 18:01
@samnazarko I tried it, still does not work for me
