### ISSUE TITLE
kernel missing br_netfilter

### ISSUE THREAD

**Issue by strowi** [osmc/osmc#713] opened 2022-10-03 15:32 UTC
Hi,

i am a heavy user of docker/kubernetes/k3s. 
I just did a fresh install of osmc on the pi4, and noticed DNS/Networking Problems in K3s.

Some networking operations require `br_netfilter` to be present. (e.g. see https://kubernetes.io/docs/setup/production-environment/container-runtimes/ ).
This seems also related to bridged devices ( https://discourse.osmc.tv/t/tethering-not-possible/22331 ) 

Would it be possible to enable this in one of the next releases? There should be no downside.

regards,
strowi

**Comment by samnazarko** [comment] 2022-10-04 01:25
Hi

I'm happy to accept a PR for PI2 and Pi4 kernel configs for this

Sam

**Comment by strowi** [comment] 2023-06-02 16:34
Hi @samnazarko ,

it's been some time... I finally got around taking a closer look and got a working kernel built using the aarch64-toolchain-osmc on amd64.
Question is: During `make rbp464` i still get asked for some other (seemingly unrelated) kernel-options like:

```bash
CONFIG_ARM64_PTR_AUTH_KERNEL=y
CONFIG_ARM64_MTE=y
GCOV_KERNEL=n
NETFILTER_XT_MATCH_PHYSDEV=n
```

Should i just add those with the defaults to the patch-file or are those handled differently? 

Otherwise it really just needs `++CONFIG_BRIDGE_NETFILTER=m`.

**Comment by samnazarko** [comment] 2023-07-03 08:29
>Question is: During make rbp464 i still get asked for some other (seemingly unrelated) kernel-options like:

Are you saying that happens with a normal make rbp464 build?
That should not occur. Or does it only occur when changing the kernel configuration?

**Comment by strowi** [comment] 2023-07-03 09:53
Yes, that was on commit `51c62ececd8edf4c1d67cbd43be04311e328c683`. At least the `NETFILTER_XT_MATCH_PYHSDEV` appears because it depends on `CONFIG_BRIDGE_NETFILTER`. But i have no idea where the others come from.

**Comment by samnazarko** [comment] 2023-07-25 00:22
Hi,

This is now fixed in: 

https://github.com/osmc/osmc/commit/ab765008104e0d936efe1d2f301f27f12ce1edf3 

I expect to get this update out for Sunday.
It is already in the staging repository. Could you please test?

1. [Login via the command line](https://osmc.tv/wiki/general/accessing-the-command-line/)
2. Run the following command to add the staging repository:
```echo 'deb http://apt.osmc.tv bullseye-devel main' | sudo tee /etc/apt/sources.list.d/osmc-devel.list```
3. Run the following commands to update: ```sudo apt-get update && sudo apt-get dist-upgrade && reboot```
4. Your system should have have received the update. 

Please see if the issue is resolved.

I also recommend you remove ```/etc/apt/sources.list.d/osmc-devel.list``` after updating. 

This will deactivate the staging repository. You can do so with the following command:
```sudo rm /etc/apt/sources.list.d/osmc-devel.list```. 

Please note that we will automatically disable this update channel after 14 days on your device in case you forget to do so to ensure that your system reverts to the stable update channel.

**Closed** 2023-09-07 22:36 UTC
