### ISSUE TITLE
nss/nspr libraries

### ISSUE THREAD

**Issue by emilsvennesson** [osmc/osmc#420] opened 2018-01-10 17:02 UTC
Hi! 

`libwidevinecdm.so`, required by some add-ons using `inputstream.adaptive` depends on the libraries `nss` and `nspr` which is currently not included in the OSMC image.

```
osmc@osmc:~$ ldd libwidevinecdm.so
        linux-vdso.so.1 (0x7ef69000)
        /usr/lib/libarmmem.so (0x76814000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x767ea000)
        libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x7673300                                                                                           0)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76720000)
        librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0x7670a000)
        libnss3.so => not found
        libnssutil3.so => not found
        libnspr4.so => not found
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76695000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x7666c000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x7657c000)
        /lib/ld-linux-armhf.so.3 (0x54af2000)
```

It would have been very nice to have this included, similar to what LibreELEC did in https://github.com/LibreELEC/LibreELEC.tv/pull/1791.

**Comment by samnazarko** [comment] 2018-01-11 03:47
Hello

Thanks for this report.

It looks like these dependencies only need to be satisfied in Kodi v18 (Leia) and later. Please let me know if that's not the case.

Can you confirm if the following commands satisfy the dependencies and work as expected:

```
sudo apt-get update
sudo apt-get install libnss3 libnspr4
```

If this works, these packages can simply be depended on by the mediacenter-osmc package; or; if we package libwidevinecdm.so directly, by the package containing it.

**Comment by emilsvennesson** [comment] 2018-01-11 16:00
I can confirm that it works after installing the libraries using `apt`, so adding them as a dependency seems like a good solution to me. :-) 

This is required for earlier versions than Kodi 18 as well, because `libwidevinecdm.so` extracted from later versions of ChromeOS all depend on `nss` and `nspr`.

**Comment by samnazarko** [comment] 2018-01-11 16:02
Thanks for confirming. I won't include this in OSMC yet as we don't include a libwidevine package as part of OSMC yet

On 11 Jan 2018, at 16:00, emilsvennesson <notifications@github.com<mailto:notifications@github.com>> wrote:


I can confirm that it works after installing the libraries using apt, so adding them as a dependency seems like a good solution to me. :-)

This is required for earlier versions than Kodi 18 as well, because libwidevinecdm.so extracted from later versions of ChromeOS all depend on nss and nspr.

-

**Comment by emilsvennesson** [comment] 2018-01-11 16:11
@samnazarko I would actually advise you to not include libwidevinecdm as part of OSMC because redistribution of the binary breaks the EULA.

```
"Google Inc. and its affiliates ("Google") own all legal right, title and
interest in and to the content decryption module software ("Software") and
related documentation, including any intellectual property rights in the
Software. You may not use, modify, sell, or otherwise distribute the Software
without a separate license agreement with Google.  The Software is not open
source software.

If you are interested in licensing the Software, please contact
widevine@google.com.
```

This is why I wrote [script.module.inputstreamhelper](https://github.com/emilsvennesson/script.module.inputstreamhelper) (available in the official Kodi repository), allowing users to grab the binary automatically in a way that complies with the EULA.

**Comment by samnazarko** [comment] 2018-01-11 16:13
Indeed -- my intention was to have a Debian package that installs it via postinst invoking wget on the target system, so that we are not actually redistributing the files ourselves.

**Comment by emilsvennesson** [comment] 2018-01-11 16:18
@samnazarko Ah, I see. You would have to extract the binary from the Chrome OS image as that's the only (afaik) official source for libwidevinecdm on ARM.

You can take a look at https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/1 for some more information on this.

**Comment by samnazarko** [comment] 2018-01-11 16:24
Cheers.

**Comment by samnazarko** [comment] 2018-08-20 03:09
We can't distribute libwidevine as part of OSMC due to licensing restrictions.
I will close this as a result

**Closed by samnazarko** 2018-08-20 03:09 UTC
