### ISSUE TITLE
CEC disconnects after switching channels or turning TV off and on (Samsung TV)

### ISSUE THREAD

**Issue by goliashcz** [osmc/osmc#342] opened 2016-12-15 13:36 UTC
Everytime I turn off the TV (the Raspberry Pi is still running) and the turn it back on, the TV remote doesn't work with the Pi anymore. Or if I switch to some TV channel and back to HDMI input.

There is a confirmation from different users on this issue:
https://discourse.osmc.tv/t/cec-problem-with-samsung-tv/

It is reproducible every time and it looks like regression from about a month ago.

I haven't found anything suspicious in kodi.log but if you could advise what log file could help you (or setting some debug level somewhere), just let me know.

**Comment by varunmaitreya** [comment] 2016-12-15 16:13
Before there wasn't a problem like this with previous version of osmc. It even happens with my LG smart TV. Had to reboot pi to get functionality.

**Comment by samnazarko** [comment] 2016-12-15 17:33
Needs a log for further investigation.

**Comment by goliashcz** [comment] 2016-12-16 08:32
Here are the log files: http://paste.osmc.io/igutizader

Actions done:
1. Turned debugging on.
2. Restarted Rasberry Pi
3. CEC is working, went to MyOSMC, logging menu
4. Turned TV off, RPi is still running.
5. Turned TV on, CEC is not working
6. Search for Anyconnect+ devices in TV menu
7. CEC is working
8. Selected Upload log files in menu

I hope this helps now. Let me know if I could help more. Thanks.

**Comment by samnazarko** [comment] 2016-12-17 01:38
Can you let me know the timepoints in the log when it works and doesn't work? What is the output of cec-client?

Please test and confirm if an older version of OSMC works, and if it does, please provide that version and a log of it working.

**Comment by goliashcz** [comment] 2016-12-17 19:05
I have tested it one more time with some delays to make the log more readible: [http://paste.osmc.io/ewezewiyen](url)

19:40 restart
19:40 - 19:40:57 clicking on remote arrows to get to Log Uploader menu item
idling for 3 min, no actions
19:45 turned off TV, turned on TV
cec is not working
idling for 3 min, no actions
19:48:24 searching for Anynet+ devices, selecting Kodi
cec is working
idling for 3 min, no actions
19:51:20 uploading logs

When I get some time (and empty SD card), I will try to install the older OSMC version.

**Comment by goliashcz** [comment] 2016-12-21 19:45
I have tested the same with 2016.10-1 and 2016.09-1 images and it doesn't work either :-(

**Comment by goliashcz** [comment] 2017-01-03 14:52
It seems it was a Samsung issue and it is fixed by 1480 firmware update released in last few days.

**Comment by samnazarko** [comment] 2017-01-03 14:54
I saw the post on the OSMC forums. This is interesting. I'd recommend turning off auto updates on your TV if things work as expected for now.

**Comment by samnazarko** [comment] 2017-01-03 16:42
@varunmaitreya Can you confirm the issue is resolved too?

If so, I'll close this.

**Closed** 2017-01-22 23:58 UTC
