### ISSUE TITLE
OSMC fails to upgrade

### ISSUE THREAD

**Issue by duch365** [osmc/osmc#388] opened 2017-08-12 08:35 UTC
Hello,

I have reproduced this several times in a row. I have a brand new 8GB SD card. I install the Raspberry Pi 1 OSMC on it (the latest available with the tool), boot on my Pi, do basic config (try to do the minimum), and then launch upgrade. 

It downloads the latest, I say Yes, exists, starts to install, and then systematically crashes (somehow a directory is not valid). Then says "Fails to install rbp1-image.4.9.29-11-osmc". I'm basically stuck...

Thanks

**Comment by samnazarko** [comment] 2017-08-12 15:55
Duplicate of forum post

**Closed by samnazarko** 2017-08-12 15:55 UTC
