### ISSUE TITLE
Wrong DNS server in resolv.conf since End Septembre Update 

### ISSUE THREAD

**Issue by davinkevin** [osmc/osmc#226] opened 2015-10-01 19:11 UTC
Hi

I have in my home network a DNS server registered in my router as my first DNS. 
Since the update of September (28 September 2015, v15.2) This server is totally ignored and not registered inside the resolv.conf files.

All was working well before the update, all the others computers of my network work well too.
And I also wait before updating all my OSMC RPI (I have three PI) and the problem occurs only after the update to the next version.

It's very problematic because I use shared database located by domain name and stream for local network with dns name too, so I can't reach this service... so my PI are almost useless right now.

Thanks for your help

**Comment by davinkevin** [comment] 2015-10-03 12:32
After investigation, connmanctl seems to be linked to the problem.

2 things : 
* connmanctl reads DNS server in reverse order from what the DHCP server send (last DNS server in first place...)
* connmanctl pick only 3 DNS server, so in my configuration, I have 4 servers, one is not inserted

The result for me with this two behavior result to be the most important DNS server, in first place to be ignore by connmanctl because of the reverse order and the limit at 3 DNS server.

Do you have an idea how I can modify this configuration ?

**Comment by davinkevin** [comment] 2015-10-03 12:58
I have the same problem with the GUI of 'My OSMC'.

If I decide to use the static configuration, the primary DNS become the second one in the /etc/resolv.conf and the secondary became the first DNS server...

Some capture of my configuration, 

With the GUI : 
![image](https://cloud.githubusercontent.com/assets/1970922/10263021/1980bd64-69df-11e5-9f87-b7ee25bbff7e.png)

And the result seen in the file with SSH : 
![image](https://cloud.githubusercontent.com/assets/1970922/10262995/ae618022-69de-11e5-971f-4af8a5090e3a.png)

**Comment by DBMandrake** [comment] 2015-11-14 23:11
Thanks - we're aware of this problem and fixing it is on our to do list.

Keep in mind however that specifying multiple DNS servers which do not give the same answers to queries is not recommended practice in general. Doing so can lead to obscure intermittent dns lookup failures even if the servers were listed in the "correct" order instead of the reverse order.

You cannot make any assumptions about the order in which a client operating system will query DNS servers or whether it will follow a particular order.

Some operating systems will query the primary server first for every lookup and only query the secondary if the primary does not respond quickly enough. (This is typical of Linux using the standard libc resolver library) However random packet loss can cause a secondary to sometimes be queried due to a non response from the primary, leaning to a hard to diagnose intermittent dns lookup failure.

Some operating systems will start by querying the primary server but if it doesn't respond in time even once it will switch to the secondary server and continue to query the secondary first, until the secondary doesn't respond and then switch back. This is typical of Linux running something like dnsmasq, and I believe that the built in dns forwarder in connman (disabled by default in OSMC) behaves similarly.

If you need to use your local DNS server to resolve local host names I would recommend you don't use 8.8.8.8 directly on your clients but configure your routers dns server to forward its queries to 8.8.8.8.

**Comment by samnazarko** [comment] 2016-09-11 01:49
The problem is fixed in OSMC's August update.

**Closed by samnazarko** 2016-09-11 01:49 UTC
