### ISSUE TITLE
compatibility with Musical Fidelity m1 dac

### ISSUE THREAD

**Issue by GTorreil** [osmc/osmc#316] opened 2016-06-25 19:21 UTC
Since 2016 release, compatibility with the Musical Fidelity m1 dac has been dropped.

**Comment by GTorreil** [comment] 2016-06-26 14:54
The musical fidelity m1 dac connects via USB and is identified by ALSA as a sound output without any driver installation. Until the January release, it worked Great, both analogic and numeric modes were supported. Now they do not work a all. I have tested with Raspberry Pi 1 (zero) and two, same problem everywhere.

**Comment by samnazarko** [comment] 2016-06-26 15:45
Closing.

You need to confirm this is actually a bug via our forum before opening an issue. This tracker is for confirmed bugs only. If it worked in the January version of OSMC, you should provide logs of the January and June versions so we can see if there are any differences. No one on the team has this hardware, so the current description of the problem is simply not enough for us to address any potential issue here.

**Closed by samnazarko** 2016-06-26 15:45 UTC
