### ISSUE TITLE
OSMC/Kodi hangs when playing RAR'd video

### ISSUE THREAD

**Issue by strigona** [osmc/osmc#385] opened 2017-08-03 02:22 UTC
Attempting to play rar'd videos seems to be hanging OSMC/Kodi. Here are the relevant logs:
```

19:05:10.857 T:1958588416  NOTICE: VideoPlayer: Opening: rar://nfs%3a%2f%2f10.0.0.23%2fmnt%2fmd0%2fdata%2fVideos%2fxxxx.720p.HDTV.x264%2fxxxx.s05e05.720p.hdtv.x264.rar/xxxx.s05e05.720p.hdtv.x264-crooks.mkv
19:05:10.857 T:1958588416 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
19:05:10.858 T:1593570288  NOTICE: Creating InputStream
19:05:11.364 T:1593570288  NOTICE: Creating Demuxer
19:05:14.313 T:1593570288  NOTICE: Opening stream: 0 source: 256
19:05:14.313 T:1593570288  NOTICE: Creating video codec with codec id: 28
19:05:14.323 T:1593570288  NOTICE: Creating video thread
19:05:14.323 T:1483731952  NOTICE: running thread: video_thread
19:05:14.323 T:1593570288  NOTICE: Opening stream: 1 source: 256
19:05:14.323 T:1593570288  NOTICE: Finding audio codec for: 86019
19:05:14.325 T:1593570288  NOTICE: Creating audio thread
19:05:14.325 T:1475343344  NOTICE: running thread: CVideoPlayerAudio::Process()
19:05:14.325 T:1593570288  NOTICE: Opening stream: 2 source: 256
19:05:14.391 T:1475343344  NOTICE: Creating audio stream (codec id: 86019, channels: 6, sample rate: 48000, no pass-through)
19:06:11.799 T:1627386864  NOTICE: ES: Client  from ::ffff:10.0.0.113 timed out
19:07:15.664 T:1496114160   ERROR: Read - Error( -14, read call failed with "'" )
19:07:15.664 T:1496114160 WARNING: underflow: Error reading file - assuming eof
19:07:15.672 T:1496114160   ERROR: filerar CFileRarExtractThread::Process failed. CmdExtract::ExtractCurrentFile threw a UnrarXLib error code of 2
19:07:23.615 T:1475343344  NOTICE: CVideoPlayerAudio::Process - stream stalled
19:07:54.395 T:1958588416  NOTICE: CVideoPlayer::CloseFile()
19:07:54.395 T:1958588416  NOTICE: VideoPlayer: waiting for threads to exit
19:07:54.904 T:1483731952 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:09:02.020 T:1627386864 WARNING: Previous line repeats 2 times.
19:09:02.020 T:1627386864  NOTICE: ES: Client  from ::ffff:10.0.0.113 timed out

```

Details:
OSMC is running on my Pi 3 B
Video is on my NAS, shared via NFS

Videos often play for several minutes before erroring out & causing Kodi to lock up. I have to SSH in and kill the Kodi process. I try to extract the video ahead of time, but I don't always know what's rar'd and what's not from the Kodi library.

If this is an upstream/Kodi issue, I'm happy to submit an issue there. I figured I'd start here.

**Comment by samnazarko** [comment] 2017-08-03 02:38
Please post a debug log using the OSMC logger
Does this happen for all videos or one particular season / scene?
Is this a new issue?

**Comment by strigona** [comment] 2017-08-03 03:25
Hi Sam,

The snippet above is all relevant logs from ~/.kodi/temp/kodi.log from the moment the play button was pressed. I'll look into the OSMC logger.

It has been happening for most if not all rar'd content. Spanning across multiple shows.

It's been happening for at least 2 months, I just haven't had the chance to look into it until now. That being said, rar'd content is also a bit new for me, so I can't be sure if this is a recent issue or just a recently surfaced issue.

I'm planning on doing a fresh install of OSMC to verify that it is in fact an issue and not an issue with my install.

**Comment by samnazarko** [comment] 2017-08-03 03:27
It's not a debug log, and only a snippet. Full logs are better because usually when people say they have included everything relevant, they haven't ;)

I'm going to close this as this should really be on the forum. The tracker is for confirmed bugs only. I'd advise reading the Wiki which will explain how to submit a support request with the necessary information to solve your problem.

**Closed by samnazarko** 2017-08-03 03:27 UTC
