### ISSUE TITLE
time sync on boot doesn't work with nfs as root fs

### ISSUE THREAD

**Issue by ggzengel** [osmc/osmc#234] opened 2015-11-04 00:57 UTC
In osmc/package/network-osmc/files/usr/bin/http-time it will parse "connmanctl state" for "online", but with booting from nfs it will never be "online".

On boot I always have to wait for 60 sec to go on.

```
# connmanctl state
  State = idle
  OfflineMode = False
  SessionMode = False
```

What's about systemd-timesyncd.service? (> even if the system lacks a battery-buffered RTC chip)

I changed /etc/systemd/timesyncd.conf and have now this one line:
NTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org

It boots now very fast and has always the right time if it's come up.

Because you use debain pools in your ntp config what's about an own pool:
http://www.pool.ntp.org/en/vendors.html

>Get your vendor zone

>To allow you to use the pool as the default time service in your application, we will set you up with special hostnames, for example 0.vendor.pool.ntp.org, 1.vendor.pool.ntp.org, 2.vendor.pool.ntp.org and 3.vendor.pool.ntp.org.

>You must absolutely not use the default pool.ntp.org zone names as the default configuration in your application or appliance.

>You can apply for a vendor zone here on the site.

>If you have an open source ntpd implementation or an operating system including ntpd, we ask that you make a reference in the configuration file or documentation encouraging people to join the pool.

>If you are a commercial / closed-source vendor we will ask for a small contribution to help scaling the pool to meet demands.

>Questions? Email ask@develooper.com.

**Comment by ggzengel** [comment] 2015-11-04 03:49
The right parameter for /etc/systemd/timesyncd.conf is:
[Time]
Servers=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org

Even if "NTP" inside the original code (https://github.com/systemd/systemd/blob/master/src/timesync/timesyncd-gperf.gperf) it don't work and fall back to default servers.
I think the debian maintainers have removed this, but why?
> Unknown lvalue 'NTP' in section 'Time'

Don't forget to activate:
$ systemctl enable systemd-timesyncd

**Comment by DBMandrake** [comment] 2015-11-04 09:47
Thanks for the heads up on the http-time service not realising it is on an NFS root install - that is indeed an oversight on my part when writing the script for the service. NFS root does not get enough testing (very few users use it apparently, and we sometimes don't get time to test it ourselves) so we don't always think about the possible side effects that a change like adding http-time.service might have on an NFS root install.

Now that you've brought our attention to it I realise that there are a couple of other places that need fixing too - including the connman-wait-for-network.service which also queries connman state, so I will fix all the instances where connman state is queried.

You seem to be a little bit confused on a couple of other points though, so I'll try to clear those up:

1) http-time.service being delayed for its full 60 seconds does not actually delay the start of Kodi. If Kodi startup is being delayed as well that is because you have enabled "Wait for network" in network settings - this is the connman-wait-for-network.service that I mentioned earlier which also queries connman state and needs fixing as well. In the mean time simply turn off wait for network to avoid this delay loading Kodi.

2) Thanks for the suggestion, but we don't need to add systemd-timesyncd.service - if you check the system journal you'll see that we already have the standard debian ntpd service installed and running - right from the very first Alpha releases of OSMC in fact. (http-time was added much later)

The sequence of events during boot is:

1) Fake hwclock restores the system time to the time that was saved at the last reboot/shudown.
2) http-time runs and sets the time by making an http query - this gets the time within about 1-2 seconds typically.
3) ntpd is started and runs continuously, keeping the time exact, typically within 0.1 seconds.

The reason we added step 2 is because a significant number of users ISP's and/or routers block udp port 123 preventing ntpd from syncing at all, in this case the time would otherwise be off by hours/days/weeks (fake hwclock restore from the last shutdown) or decades... (Jan 1970...)

This way any users who have udp port 123 blocked will still get the time set close enough when booting - it will eventually drift a small amount but this is better than the time being completely wrong. For those users who do not have udp port 123 blocked, ntpd will take over and correct the time exactly.

**Comment by ggzengel** [comment] 2015-11-04 13:10
Sometimes for round about 3 min I get unixtime 0 (1.1.1970 ?), even if network is online, because I boot from nfs.
So I have 1970 as last login time (I use profiles on kodi) and I think emby add-on don't like this, too.

I activated to wait for network in hope to slow down start up a little bit to get ntp time. So I got 60 sec which is long enough the most time. But sometime it needs more than 1 min for ntp sync. With systemd-timesyncd I get the last shutdown time if ntp needs long time.

I have a local time server, which is set with dhcp, but with dhcp configured in kernel cmdline it doesn't work. There is no script (or connman) to setup network.
I have just seen that I still have time shift and I will change to local ntp now.

I think to have more time sources to ask parallel and to give the user an option to choose a local ntp is better.
systemd-timesyncd has the charm to get the last shutdown down time which is more real time than 1970.

1. Use ntp from dhcp or manually set, which is standard on debian. But call ntp-wait (needs perl).
2. Use ntp from dhcp or manually set with timesyncd (is always included in osmc), which can really set last shutdown time as new time.
3. Use a script (http-time) to get time from an http server which you trust. Perhaps the user can choose a http server (the most local router will have exact time too). First try local gateway as http time source.

To move from ntpd to timesyncd is a real option. So I would use option 2 and 3.
To have a good time source is essential for debugging. The most files are opened early and they have always a time stamp from 1970.

I do a lot of set-up of networks in germany (even business and private) and never had a blocked ntp server. But I have seen a lot of weak internet connections with a high packet lost.

**Comment by DBMandrake** [comment] 2015-11-04 13:58
The problem you reported has been fixed in the following commits:

https://github.com/osmc/osmc/commit/7c70407664c495253f72859916e7957e888f3b14

https://github.com/osmc/osmc/commit/c57f5799c13127aec8b47f5da1266f369e5c0de4

>I have a local time server, which is set with dhcp, but with dhcp configured in kernel cmdline it doesn't work. There is no script (or connman) to setup network.

At the moment we don't support setting ntp servers via DHCP - connman does have a built in ntp client but (a) you won't be able to use that with an nfsroot install as connman is not handling DHCP for nfsroot, and (b) we patched it out of connman because it was conflicting with ntpd. For various reasons we would rather use ntpd rather than the ntp client built into connman.

>I think to have more time sources to ask parallel and to give the user an option to choose a local ntp is better.

ntpd will already try to connect to up to 4 time sources automatically to improve accuracy and reliability. You can customise the servers used in /etc/ntp.conf

>systemd-timesyncd has the charm to get the last shutdown down time which is more real time than 1970.

>To have a good time source is essential for debugging. The most files are opened early and they have always a time stamp from 1970.

We already get this functionality from "fakehwclock" which is a service that saves the time on shutdown/reboot and restores it during startup. You will only get 1970 if this failed for some reason. (For example an unclean shutdown)

>I do a lot of set-up of networks in germany (even business and private) and never had a blocked ntp server. But I have seen a lot of weak internet connections with a high packet lost.

The issue is source (not destination) port 123 being blocked - probably by their router. Enough users experienced this issue and complained about it that we decided to add http-time.service - which is a re-implementation of an idea that was originally done in Raspbmc.

**Closed by DBMandrake** 2015-11-04 13:58 UTC
