### ISSUE TITLE
Unable to update third party addons due to modified hash file logic

### ISSUE THREAD

**Issue by djp952** [osmc/osmc#517] opened 2019-07-03 19:07 UTC
Hi! I am the author of a third party binary addon for Kodi that works fine with OSMC, but is unable to auto-update due to the repository being stored on a site (GitHub) that does not support the "?sha256" syntax to generate the SHA256 hash.

OSMC Version: 2019.06-1
Platform: Raspberry Pi 2/3

I tracked the issue down to the patch being applied to the stock xbmc\addons\Repository.cpp file.

```
  // Probably OSMC mirror

  if (hash.Empty())
  {
    // Expected hash, but none found -> fall back to old method
    if (!FetchChecksum(path + "?" + hashTypeStr, hash.value) || hash.Empty())
    {
      CLog::Log(LOGERROR, "Failed to find hash for {} from HTTP header and in separate file using querystring", path);
      return {};
    }
  }
  if (hash.Empty())
  {
    // Expected hash, but none found -> fall back to old method
    if (!FetchChecksum(path + "." + hashTypeStr, hash.value) || hash.Empty())
    {
      CLog::Log(LOGERROR, "Failed to find hash for {} from HTTP header and in separate file using file extension", path);
      return {};
    }
  }
```

As authored, if the attempt to acquire the SHA256 hash via ?sha256 succeeds but doesn't actually return a hash (GitHub's storage will simply return the base file, for example), whatever came back will be used as if it were a hash and lead to a mismatch.  Again using GitHub storage as the example, the code thinks the .zip file is the hash, and it never goes out to get the .sha256 file as stock Kodi would:

> 2019-07-03 00:08:56.063 T:1344262880   ERROR: CAddonInstallJob[pvr.hdhomerundvr]: Hash mismatch after download. Expected **PK   dN҄  N     pvr.hdhomerundvr/addon.xml\YwF~EX<mqb{",)&Rt@Q[**, was ba5f985df8b57d071c57fd463957a6fe56277d8e0b37b457c830e2e874658b1d

I would like to suggest that the patch be modified so that the stock Kodi method of looking for the .hash file (.sha256 in my case) occurs first, and if not found then fall back into the custom ?hash method.

If that is not acceptable an alternate suggestion would be to figure out a way to ensure that the result from a ?hash query is indeed a hash instead of a binary file, an HTML redirect page, etc., leave the hash empty if it fails that test, and then fall into the .hash method instead of just erroring out.

Thank you, I appreciate your time.

**Comment by samnazarko** [comment] 2019-07-03 22:36
Thanks for the report.
I'll take care of this.

**Comment by samnazarko** [comment] 2019-07-04 00:06
I've updated Varnish VCL on our servers to respond to .sha256,so the patch should no longer be necessary. I've kicked these builds off with Jenkins, and they should be in some hours. 

Can you please:

1. [Login via the command line](https://osmc.tv/wiki/general/accessing-the-command-line/)
2. Edit the file ```/etc/apt/sources.list```
3. Add the following line: ```deb http://apt.osmc.tv stretch-devel main```
4. Run the following commands to update: ```sudo apt-get update && sudo apt-get dist-upgrade && reboot```
5. Your system should have have received the update. 

Please see if the issue is resolved.

I also recommend you edit ```/etc/apt/sources.list``` again and remove the line that you added after updating. This will return you to the normal update channel.

**Comment by djp952** [comment] 2019-07-04 03:55
Fantastic, thank you so much.  I will confirm the functionality as soon as I get the update installed.

I truly appreciate the time spent on this, and so fast too!

**Comment by djp952** [comment] 2019-07-04 21:42
Update received, works perfectly.  Thank you again sir.  LMK if you want me to close this issue or if you typically do it, please feel free! I'll let the gang know that this won't be a problem with the next OSMC release.

**Comment by samnazarko** [comment] 2019-07-04 22:06
Thanks for confirming that this is now resolved and for the initial report. Things look good here with the OSMC repo too, so happy to close this.

**Closed by samnazarko** 2019-07-04 22:06 UTC
